resources:
  - ../../base
namePrefix: dev-
commonLabels:
  env: dev
patches:
  - target:
      kind: Deployment
      name: demo
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: APP_NAME
          value: "dev-demo"
