apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels: { app: demo }
spec:
  replicas: 1
  selector:
    matchLabels: { app: demo }
  template:
    metadata:
      labels: { app: demo }
    spec:
      containers:
      - name: web
        image: rlawnsdud/demo:arm
        ports:
        - containerPort: 3030
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "3030"
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels: { app: demo }
spec:
  selector: { app: demo }
  ports:
  - name: http
    port: 80
    targetPort: 3030
